version: "3.2"
services:
  db:
    container_name: "db"
    image: "postgres:13"
    ports:
      - "54320:5432"
    environment:
      POSTGRES_DB: "bugtracker"
      POSTGRES_PASSWORD: "martinez"
    restart: always

volumes:
  db-data:
    name: db-data
